#
# ELIB - library of MSC/TC compatible functions
#        and old MASM/new MASM/TASM compatible too
#

# Currently this makes a library of small model functions,
# to make large model, change MODEL=-ml and AFLAGS=... -DFUNC_L=1
#
CFLAGS= -a -d -f- -G -O -Z -DMSDOS -IL:\borlandc\include
MODELS=-ms
MODELL=-ml

# Assembler flags
AFLAGS=-mx -t
AMODELS=-dFUNC_L=0
AMODELL=-dFUNC_L=1

# Define PC-specific include file

.c.obj:
        bcc -c $(MODELS) $(CFLAGS) $*.c
        tlib ..\lib\wattcpsm -+$*
        bcc -c $(MODELL) $(CFLAGS) $*.c
        tlib ..\lib\wattcplg -+$*

.asm.obj:
        tasm $(AFLAGS) $(AMODELS) $*;
        tlib ..\lib\wattcpsm -+$*
        tasm $(AFLAGS) $(AMODELL) $*;
        tlib ..\lib\wattcplg -+$*

start: elib.lib

ELIB.LIB: QMSG.OBJ OUTHEXES.OBJ BACKGRND.OBJ DOSLIST.OBJ KEEP.OBJ OUTCH.OBJ \
OUTHEX.OBJ OUTS.OBJ OUTSN.OBJ INTEL.OBJ INCHKSUM.OBJ QMOVE.OBJ QCMP.OBJ \
SEMAPHOR.OBJ TIMEOUT.OBJ STRINGS.OBJ ISSTRING.OBJ

